M48
; DRILL file {KiCad (6.0.11)} date Fri Mar 31 13:58:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-31T13:58:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.665
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.670
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.680
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.700
%
G90
G05
T1
X101.335Y-91.44
T2
X98.988Y-82.681
X98.991Y-100.193
T3
X100.547Y-81.781
X103.135Y-91.44
T4
X100.55Y-101.093
T0
M30
